#' Convert FeatureCounts to CPM (counts per million reads)
#'
#' This function converts a Merged featureCounts table into CPM table. Merged FeatureCounts table is generated by
#' [MergeFeatureCounts()].
#'
#' This function create two files: a table containing CPM in each sample
#' and a table containing average CPM among all samples.
#'
#' @param counts_matrix A Merged featureCounts table generated by [MergeFeatureCounts()].
#' @param Assay File prefix of the outputs".
#' @export

###################### CPM Calculation ########################
CPM_c <- function(counts_matrix, Assay)
{
  countdata<-counts_matrix
  cpm <- t(t(countdata)/colSums(countdata) * 1000000)#CPM
  avg_cpm <- data.frame(avg_cpm=rowMeans(cpm))
  write.csv(cpm, paste(Assay, "_cpm.csv", sep = ""))
  write.csv(avg_cpm, paste(Assay, "_avg_cpm.csv", sep = ""))
}


